export const devilFruits = {
  paramecia: [
    {
      name_jap: "Gomu Gomu",
      name_eng: "Gum-Gum",
      type: "Paramecia",
      image: "/images/GomuGomu.png",
    },
    {
      name_jap: "Bora Bora",
      name_eng: "Chop-Chop",
      type: "Paramecia",
      image: "/images/BoraBora.png",
    },
    {
      name_jap: "Baku Baku",
      name_eng: "Munch-Munch",
      type: "Paramecia",
      image: "/images/BakuBaku.png",
    },
    {
      name_jap: "Hana Hana",
      name_eng: "Flower-Flower",
      type: "Paramecia",
      image: "/images/HanaHana.png",
    },
    {
      name_jap: "Awa Awa",
      name_eng: "Bubble-Bubble",
      type: "Paramecia",
      image: "/images/AwaAwa.png",
    },
    {
      name_jap: "Ope Ope",
      name_eng: "Awa-Awa",
      type: "Paramecia",
      image: "/images/OpeOpe.png",
    },
    {
      name_jap: "Bomu Bomu",
      name_eng: "Bomb-Bomb",
      type: "Paramecia",
      image: "/images/BomuBomu.png",
    },
    {
      name_jap: "Doru Doru",
      name_eng: "Wax-Wax",
      type: "Paramecia",
      image: "/images/DoruDoru.png",
    },
    {
      name_jap: "Ito Ito",
      name_eng: "String-String",
      type: "Paramecia",
      image: "/images/ItoIto.png",
    },
    {
      name_jap: "Sube Sube",
      name_eng: "Slip-Slip",
      type: "Paramecia",
      image: "/images/SubeSube.png",
    },
    {
      name_jap: "Kiro Kiro",
      name_eng: "Kilo-Kilo",
      type: "Paramecia",
      image: "/images/KiroKiro.png",
    },
    {
      name_jap: "Yomi Yomi",
      name_eng: "Revive-Revive",
      type: "Paramecia",
      image: "/images/YomiYomi.png",
    },
    {
      name_jap: "Horo Horo",
      name_eng: "Hollow-Hollow",
      type: "Paramecia",
      image: "/images/HoroHoro.png",
    },
    {
      name_jap: "Kage Kage",
      name_eng: "Shadow-Shadow",
      type: "Paramecia",
      image: "/images/KageKage.png",
    },
    {
      name_jap: "Nikyu Nikyu",
      name_eng: "Paw-Paw",
      type: "Paramecia",
      image: "/images/NikyuNikyu.png",
    },
    {
      name_jap: "Mochi Mochi",
      name_eng: "Mochi-Mochi",
      type: "Paramecia",
      image: "/images/MochiMochi.png",
    },
    {
      name_jap: "Mero Mero",
      name_eng: "Love-Love",
      type: "Paramecia",
      image: "/images/MeroMero.png",
    },
    {
      name_jap: "Jiki Jiki",
      name_eng: "Magnet-Magnet",
      type: "Paramecia",
      image: "/images/JikiJiki.png",
    },
    {
      name_jap: "Mane Mane",
      name_eng: "Clone-Clone",
      type: "Paramecia",
      image: "/images/ManeMane.png",
    },
    {
      name_jap: "Supa Supa",
      name_eng: "Dice-Dice",
      type: "Paramecia",
      image: "/images/SupaSupa.png",
    },
    {
      name_jap: "Uta Uta",
      name_eng: "Sing-Sing",
      type: "Paramecia",
      image: "/images/UtaUta.png",
    },
    {
      name_jap: "Gasha Gasha",
      name_eng: "Clank-Clank",
      type: "Paramecia",
      image: "/images/GashaGasha.png",
    },
  ],
  zoan: [
    {
      name_jap: "Hito Hito",
      name_eng: "Human-Human",
      type: "Zoan",
      model: "Human",
      image: "/images/HitoHito.png",
    },
    {
      name_jap: "Ushi Ushi",
      name_eng: "Ox-Ox",
      type: "Zoan",
      model: "Bison",
      image: "/images/UshiUshi.png",
    },
    {
      name_jap: "Inu Inu",
      name_eng: "Dog-Dog",
      type: "Mythical Zoan",
      model: "Okuchi no Makami",
      image: "/images/InuInu.png",
    },
    {
      name_jap: "Neko Neko",
      name_eng: "Cat-Cat",
      type: "Zoan",
      model: "Leopard",
      image: "/images/NekoNeko.png",
    },
    {
      name_jap: "Uo Uo",
      name_eng: "Fish-Fish",
      type: "Mythical Zoan",
      model: "Azure Dragon",
      image: "/images/UoUo.png",
    },
    {
      name_jap: "Hebi Hebi",
      name_eng: "Snake-Snake",
      type: "Mythical Zoan",
      model: "Yamata no Orochi",
      image: "/images/HebiHebi.png",
    },
    {
      name_jap: "SMILE",
      name_eng: "Snake-Snake",
      type: "Artificial Zoan",
      image: "/images/SMILE.png",
    },
  ],
  logia: [
    {
      name_jap: "Suna Suna",
      name_eng: "Sand-Sand",
      type: "Logia",
      image: "/images/SunaSuna.png",
    },
    {
      name_jap: "Yami Yami",
      name_eng: "Dark-Dark",
      type: "Logia",
      image: "/images/YamiYami.png",
    },
    {
      name_jap: "Mera Mera",
      name_eng: "Flame-Flame",
      type: "Logia",
      image: "/images/MeraMera.png",
    },
    {
      name_jap: "Moku Moku",
      name_eng: "Smoke-Smoke",
      type: "Logia",
      image: "/images/MokuMoku.png",
    },
    {
      name_jap: "Goro Goro",
      name_eng: "Rumble-Rumble",
      type: "Logia",
      image: "/images/GoroGoro.png",
    },
  ],
};
